version: '3.8'

services:
  db:
    container_name: sql-learning-postgres
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: learn
      POSTGRES_USER: learn
      POSTGRES_DB: learn
    volumes:
    - pg-data:/var/lib/postgresql/data

  pgadmin:
    container_name: sql-learning-pgadmin
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: pdmmichaelsen@gmail.com
      PGADMIN_DEFAULT_USERNAME: learn
      PGADMIN_DEFAULT_PASSWORD: learn
    ports:
      - "5050:80"
    links:
    - "db:sql-learning-postgres"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  pg-data:
  pgadmin-data: