version: '3.8'

services:
  db:
    container_name: sql-learning
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: "learn"
      POSTGRES_USER: "learn"
      POSTGRES_DB: "learn"

  pgadmin:
    container_name: sql-learning-pgadmin
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: pdmmichaelsen@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    links:
    - "db:sql-learning"